pull request
if-tech-support/todo_team pull request #14
Opened 2021-11-07 07:57 UTC by tetsu633

2021-11-11 14:35 UTC, Junkichi89 requested changes
@tetsu633 
実装ありがとうございました。
気になる箇所を何点か指摘させていただきました。
基本的には、レイアウトもしっかりと組めていたので問題ないかと思います。

コメント内容を確認していただき、再度修正をお願いいたします。
コメント内容がわかりづらい場合は、質問してください。
よろしくお願いいたします。

2021-11-11 14:35 UTC, Junkichi89 commented on src/App.css
> +
不要な余白は削除しましょう。
他の箇所も同様です。

2021-11-11 14:35 UTC, Junkichi89 commented on src/App.js
> +    limit: "2021-11-15",
期限の実装は少し難易度が高いので、一旦、なしでよろしいでしょうか？

2021-11-11 14:35 UTC, Junkichi89 commented on src/App.js
> +  { id: 2, title: "sample2", status: "Done", limit: "2021-11-20" },
他の項目と体裁を合わせましょう。

2021-11-11 14:35 UTC, Junkichi89 commented on src/App.js
> +                <tr key={index}>
keyに設定する値は、一意になる値にしましょう。
keyにindexを指定するのは非推奨です。
https://ja.reactjs.org/docs/lists-and-keys.html#keys

2021-11-11 14:35 UTC, Junkichi89 commented on src/App.js
> +                        <button className="btn">Detail</button>
ボタンの色、分けてもらってもいいでしょうか？
一緒だと違いが分かりづらいので、好きな色で構いませんので、よろしくお願いします。

2021-11-11 14:35 UTC, Junkichi89 commented on src/App.css
> +}
ここ分ける必要ないと思います。heightを設定している箇所と同様に設定してしまって大丈夫かと思います。
thead部分のbottomのborderは不要かと思います。

2021-11-11 23:52 UTC, tetsu633 commented on src/App.js
> +    limit: "2021-11-15",
なしで良いと思いますので削除します

2021-11-12 00:24 UTC, tetsu633 commented
@Junkichi89 
以下修正致しましたのでご確認お願いいたします。

## 対応内容
- 不要な余白の削除、リファクタリング
- Todoデータ 「期限」の削除
- ボタンの色の変更

2021-11-12 14:07 UTC, Junkichi89 commented on src/App.css
> +  height: 60px;
こちらは入れておいてもらって大丈夫かと思います。
`border-top: 1px solid #d3d3d3;`

2021-11-12 14:07 UTC, Junkichi89 commented on src/App.css
> +.detail-btn {
色だけを指定するためにclassをつけるのであれば、btn-detailやbtn-deleteなどとした方がわかりやすいですね。

bootstapとかだとこんな感じですね。
https://getbootstrap.jp/docs/5.0/components/buttons/#button-tags

2021-11-12 14:16 UTC, Junkichi89 requested changes
修正お疲れ様でした。
再度何点か指摘させていただきました。
今回のチーム開発でCSSはメインでないですが、気になる箇所を指摘させていただきました。
よろしくお願いいたします。

こちらの内容修正いただきましたら、
一旦、こちらのissueはOKかと思います。

2021-11-12 14:16 UTC, Junkichi89 commented on src/App.css
>  }
こちら、あえて、初めのレビューでは、記載しなかったのですが、
なるべくHTMLとスタイリングは疎結合である方が望ましいというのが一般的な見解かと思います。

今回は、CSSについての学習はメインではないので、Tableについては、そのままでも問題ないですが、変更される可能性が高い箇所は、なるべくclassをつけてスタイリングを行いましょう。
ulやliなど、その役割に応じたclassをつけてください。

2021-11-19 23:58 UTC, tetsu633 commented
@Junkichi89 
修正遅くなりすいません。
以下修正致しましたのでご確認宜しくお願いします！

## 対応内容
1. ぱんくずリスト、ヘッダーのコンポーネント化
    コンポーネント（ヘッダー、ぱんくずリスト）はcomponentsフォルダ、cssファイルが増えてきたのでstyleフォルダへ格納するようにしています
2. リスト一覧表示のレイアウト調整
3. リファクタリング

1, 2はこちらで対応しました
a802b1c55e6ca1e97b1ff4cbac865cd301b4564f

3に関してはこちらで対応しました
0da4749469ad094b0aa350e9f8188fe6b6db649d

## やってないこと・できていないこと
- レイアウトのみの作成のためボタンの処理、テーブルのタイトルをアンカーではなくpタグで書いています
- アイコンの設定はどのようにするのが良いでしょうか？
  イメージフォルダに入れる or CDNを利用する等でしょうか？
- ぱんくずリストの表示を画面ごとに変更する方法が思いつかなかったため各画面でぱんくずリストのコンポーネントにprops表示するぱんくずリストの配列を渡しています

2021-11-20 10:26 UTC, Junkichi89 requested changes
気になる箇所はコメントに記載させていただきました。
機能実装の際に変更になる箇所も多いと思うので、細かくは指摘していないので
機能実装の際に修正していければと思います。

画像のように、編集ボタンの位置がズレてしまっているので調整してもらえますか？

よろしくお願いします。
コメントと上記の部分の修正が終われば、すぐにマージできればと思いますので、
よろしくお願いします。

![image](https://user-images.githubusercontent.com/65665381/142722823-bda018fc-169c-49b3-88c9-c8b456eed8fe.png)
![image](https://user-images.githubusercontent.com/65665381/142722865-c6bff1ce-d6f6-4008-9a9f-79c92fbe8815.png)

2021-11-20 10:26 UTC, Junkichi89 commented on src/components/Breadcrumb.jsx
> +        {breadcrumbElements.map((element) => (
ここは、(element)ではなく、({ id, title })としてしまっても大丈夫です。
気になるようでしたら、修正してください。
（そのままでも大丈夫です)

2021-11-20 10:26 UTC, Junkichi89 commented on src/routes/ListView.jsx
> +              <th>タスク名</th>
空の要素を入れるのはあまり推奨できないので、
`<th colSpan="2">タスク名</th>`
としておきましょう！

2021-11-20 10:26 UTC, Junkichi89 commented on src/routes/ListView.jsx
> +                    <button className="btn-edit">✎</button>
こちらのbuttonもtdに入れた方が良さそうですね！

2021-11-20 10:42 UTC, Junkichi89 commented
@tetsu633 
> レイアウトのみの作成のためボタンの処理は記載なし、テーブルのタイトルをアンカーではなくpタグで書いています
OKです！
こちらは機能実装で修正していきましょう！

> アイコンの設定はどのようにするのが良いでしょうか？
> イメージフォルダに入れる or CDNを利用する等でしょうか？
そうですね、画像ファイル入れるならassetsとかディレクトリをつくてimagesとかでいいように思いますが、
アイコンだけなので、react-iconなどのライブラリー入れてしまっていいと思います！
似たようなアイコン探して使うで問題ないですかね

> ぱんくずリストの表示を画面ごとに変更する方法が思いつかなかったので各画面でぱんくずリストコンポーネントのpropsに表示するリストを渡しています
> ⇒こちら表示項目をuseContextで状態管理して、画面遷移のボタンに内容を変更する処理を入れるのが良いでしょうか？

そうですね、他に思いつく実装があるのであれば、変更してもらっても大丈夫ですが、一旦、全体的にこちらのIssueは反映したいので、修正は別Issueにさせていただいてもよろしいでしょうか？
個人的にはreact-routerを使って取れる値によって、pageによって出し分ける方がいいかなとは思いますかね。

2021-11-20 23:15 UTC, tetsu633 commented
@Junkichi89 
お疲れ様です！
以下修正しましたのでご確認お願いします！
よろしければマージの方実施します！

## 対応内容
指摘内容の修正

- ぱんくずリスト展開時の引数の修正
https://github.com/if-tech-support/todo_team/pull/14#discussion_r753658707

- listviewのテーブルヘッダーの一部結合
https://github.com/if-tech-support/todo_team/pull/14#discussion_r753659318
https://github.com/if-tech-support/todo_team/pull/14#discussion_r753659982

2021-11-20 23:59 UTC, Junkichi89 reviewed
ミス

2021-11-21 00:00 UTC, Junkichi89 approved these changes
ミス

2021-11-21 00:09 UTC, tetsu633 commented
> 
ありがとうございます！
了解しました！

2021-11-21 00:11 UTC, merged