#4_cretate_detailpage
if-tech-support/todo_team pull request #15
Opened 2021-11-07 09:02 UTC by tsubasa-tahara

#4_create detailpage：詳細画面のページだけ作りました

2021-11-07 12:43 UTC, Junkichi89 commented
@tsubasa-tahara 

Issueとプルリクが紐ついていないので、以下画像を参照して紐つけてもらうようにお願いします。

![image](https://user-images.githubusercontent.com/65665381/140645332-bab1558a-b6ea-4119-ae9e-5b3f8cc65f35.png)

2021-11-30 13:36 UTC, tsubasa-tahara commented
## IssueのURL
https://github.com/if-tech-support/todo_team/issues/4
https://github.com/if-tech-support/todo_team/issues/23

## 対応内容・対応背景・妥協点
- Detailページの作成
- ListView画面のタスク名を押下するとDetailページへ遷移する
- Detailページにはatom.jsにあるダミーデータを表示する
- Detailページの戻るボタンを押下するとListView画面に戻る

## やっていないこと
- Detail.cssの書き方にもっといい方法がないかの追求
- Detailページに遷移するときに、URLパラメータにIDを渡す

## テスト
- ListViewのタスクを表示した際に内容がDetailへ反映されていること

2021-11-30 23:55 UTC, Junkichi89 requested changes
@tsubasa-tahara 
実装ありがとうございます。

デザイン通りに作ってもらっているところ悪いのですが、
編集画面や作成画面と同じようにボーダーの中にテキストが入るようになっていますが、
見た目的にuserからするとinput要素なのかなとなってしまうのかなと思いました。
なんか編集できそうみたいな認識をもたれてしまう？

なので、枠線（ボーダー）はなくしてしまった方がわかりやすいと思いますが、
どうでしょうか？

一点、もう少し工夫できそうな箇所を指摘しましたので、
対応よろしくお願いします。

2021-11-30 23:55 UTC, Junkichi89 commented on src/routes/Detail.jsx
> +        </div>
この辺りがnameとdescriptionと同じような構造で4つ並んでいるので、一つにできるとスッキリすると思います。
西村さんのstatusを切り替える際に行ったプルリクで似たような指摘しているので、参考にしてもらえるといいと思います。
少し、工夫必要な箇所なのでチャレンジしてみてください。

2021-11-30 23:55 UTC, Junkichi89 commented on src/routes/Detail.jsx
> +  console.log(state);
確認用のログは消しておいてください。

2021-12-01 00:01 UTC, Junkichi89 commented on src/routes/Detail.jsx
> +  const state = location.state;
これ使っていますか？

2021-12-11 06:41 UTC, Junkichi89 approved these changes
LGTM
![LGTM](https://image.lgtmoon.dev/149942)

2021-12-11 06:48 UTC, tsubasa-tahara commented
fix detail page

2021-12-11 06:48 UTC, merged