#2 create add page
if-tech-support/todo_team pull request #16
Opened 2021-11-07 09:37 UTC by MTaGn

test closes #2

2021-11-18 14:14 UTC, MTaGn commented
#2 
やったこと：作成画面の実装

表示方法：index.jsに<Create />をimportする
[https://i.gyazo.com/389d372c031dba7dc3bdaad44439600d.png](url)

対応内容：デザインしていただいたfigmaの画面に沿って実装

妥協点1：フォントサイズやinputボックスの高さをfigmaのCSSにしたがって実装すると縦スクロールが発生しているため、縦スクロールをさせないように上記項目の各サイズを調整するか等、使用についてきめる
下の画像は縦スクロールが発生し、追加ボタンなどが見切れているもの
[https://i.gyazo.com/31b053a0b457bd00aaa5ba7d89740086.png](url)

妥協点2：インライン要素であるlabelタグとinputタグ(タイトルと内容の箇所)がなぜか横並びしないため、flexboxを使用して横並びしている。flexboxを使用せずに横並びさせたい

妥協点3：ぱんくずが動的ではなく、テキストをべたで記述している

テスト方法：figmaと実装画面を見た目で比較？

2021-11-18 15:10 UTC, Junkichi89 requested changes
> 妥協点1：フォントサイズやinputボックスの高さをfigmaのCSSにしたがって実装すると縦スクロールが発生しているため、縦スクロールをさせないように上記項目の各サイズを調整するか等、使用についてきめる
> 下の画像は縦スクロールが発生し、追加ボタンなどが見切れているもの

一旦、縦スクロールはそのままで問題無いです。
対応するとしたら要素の余白を調整するかHeaderをもう少し小さくするかですかね・・・
UIに関しては、多少不完全でも致し方ないので、こちらは現状でもOKです。

> 妥協点2：インライン要素であるlabelタグとinputタグ(タイトルと内容の箇所)がなぜか横並びしないため、flexboxを使用して横並びしている。flexboxを使用せずに横並びさせたい

横幅を100%にしている箇所があるので絡む落ちしています。
横幅を指定すれば横並びにすることは可能ですが、flexの方が
要素を可変にできるので便利なのでなるべくflexでレイアウト組んでもらって大丈夫です。
できればlabel部分の幅を固定して、inputやtextarea の部分だけ可変にしてもらえるといい感じになると思います。

以下の画像の赤枠の部分を揃えたいですね。
![image](https://user-images.githubusercontent.com/65665381/142441247-80fdbbfe-a776-461b-a695-8f07ba6ce4dd.png)


> 妥協点3：ぱんくずが動的ではなく、テキストをべたで記述している

すみません、このIssueではheader部分の対応不要となりました。
失礼しました。

たくさん指摘をさせていただきましたが、修正不要なものもあります。
また、同じ内容は2回指摘していない箇所もあるので、一旦全て修正、確認したら同じように修正できないか見直してもらえるといいかと思います。

できない箇所はできないとコメントして飛ばしてもらっても大丈夫です。
ちょっと大変かと思いますが、よろしくお願いします！

2021-11-18 15:10 UTC, Junkichi89 commented on src/CreateComponent/Create.css
> +}
不要な記述はなるべく残さないようにしましょう。
基本的に申し送りなど、誰かに何かを伝える以外のコメントは残さないように気をつけてください。

2021-11-18 15:10 UTC, Junkichi89 commented on src/CreateComponent/Create.css
> +}
すみません、今回は、ルーティングの設定を西村さんが担当いただいたので、ヘッダーとパンくずリストは西村さんのIssueで共通化を進めてもらっています。

なので、このissueでは対応不要になります、
すみませんが、削除お願いします。

2021-11-18 15:10 UTC, Junkichi89 commented on src/CreateComponent/Create.css
> +  margin: auto auto auto 56px;
削除するエリアのため、修正は不要ですが。
margin: auto auto auto は不要かとおもいます。
margin: 0;で
containerの方でpaddingを設定する方が綺麗にまとまるとおもいます。

2021-11-18 15:10 UTC, Junkichi89 commented on src/CreateComponent/Create.css
> +  position: relative;
ここも修正不要ですが、このposition: relativeは何のために指定していますか？
不要なら削除しましょう。

2021-11-18 15:10 UTC, Junkichi89 commented on src/CreateComponent/Create.css
> +  background-color: #4E758D;
ここも修正不要ですが、ここは二重に背景を指定する必要はありますか？
不要な記述は削除しましょう。

2021-11-18 15:10 UTC, Junkichi89 commented on src/CreateComponent/Create.css
> +  font-style: normal;
修正不要ですが。。。

こちら不要ですよ！
Figamaからコピペして終わらずに、どのような意味があるCSSなのか確認しましょう。

2021-11-18 15:10 UTC, Junkichi89 commented on src/CreateComponent/Create.js
> +        </div>
ヘッダー共通化は別Issueで対応してもらっているので、修正せずに削除でお願いしますが、
パンクズリストはおそらくheaderの子要素に入れるのはあまり一般的ではないようにおもいます。
また、navで囲って、ulやolのタグを使うのが一般的ですかね。

いろんなサイト確認してみてください。

2021-11-18 15:10 UTC, Junkichi89 commented on src/CreateComponent/Create.js
> +
こちら使用されていないと思うので、こちらのIssueでは削除お願いします。

2021-11-18 15:10 UTC, Junkichi89 commented on src/CreateComponent/Create.js
> +      <div className="contents-container">
これ入りますか？
何か理由があって指定しているなら残してもらっても大丈夫ですが、
理由がなければ削除してください。

2021-11-18 15:10 UTC, Junkichi89 commented on src/CreateComponent/Create.js
> +                onChange={"タイトル取得関数：handleAddFormChanges"}
こちらは、このissueでは指定不要なので削除してください。

2021-11-18 15:10 UTC, Junkichi89 commented on src/CreateComponent/Create.js
> +                value={todoTitle}
valueも設定不要です。

2021-11-18 15:10 UTC, Junkichi89 commented on src/CreateComponent/Create.js
> +                onChange={"詳細取得関数：handleAddFormChangesForDetail"}
上記に同じく。不要です。

2021-11-18 15:10 UTC, Junkichi89 commented on src/CreateComponent/Create.js
> +                label="タイトル"
inputの属性にlabelって設定できるのでしたでしょうか？
設定できないと思うのですが・・・

labelと関連づけを行う場合は、forとidを使用しましょう！
他の箇所も同様の修正お願いします。

2021-11-18 15:10 UTC, Junkichi89 commented on src/CreateComponent/Create.js
> +              <option className="default">--------------------</option>
デザインでは、初期値が設定されていませんが、未着手が初期値で問題無いと思いますので、修正お願いします。
また、オプションは「未着手・進行中・完了」ですが、確かMTGでも話したと思いますが、
ステータスは追加のコンポーネントでは不要にしたので、削除しておいてください。
編集では必要になるので、よろしくお願いします。

2021-11-18 15:10 UTC, Junkichi89 commented on src/CreateComponent/Create.js
> +              <option className="default">--------------------</option>
デザインとは見た目変わりますが、一旦、中を初期値にしておいてもらえますか？

2021-11-18 15:10 UTC, Junkichi89 commented on src/CreateComponent/Create.js
> +          </div>
この辺は不要です。
削除しましょう！

2021-11-18 15:10 UTC, Junkichi89 commented on src/CreateComponent/Create.css
> +.text-container
名前が似ていてわかりづらいです。
また、テキストなら両方テキストなので勘違いを生みやすいので違う命名にしましょう。

2021-11-18 15:10 UTC, Junkichi89 commented on src/CreateComponent/Create.css
> +  width: 70%;
これは70%にした理由はありますか？
親コンポーネントで幅は設定すればこちらで設定不要ですね。

2021-11-18 15:10 UTC, Junkichi89 commented on src/CreateComponent/Create.css
> +}
reset.cssを効かせていないのが原因ではありますが、
CSS設計的には親要素やBlock要素と呼ばれるものにmarginを設定するのは、
レイアウトを作りづらくなるので、控えましょう。

今回は、他に方法が思いつかなければそのままでも大丈夫です。（CSSはメインでは無いので・・・）

2021-11-18 15:10 UTC, Junkichi89 commented on src/CreateComponent/Create.css
> +  height: 47px;
inputもtextareaも高さを設定する必要はないと思います。
textareaはHTML側で調整してください。
inputはpaddingで調整してみましょう！

2021-11-18 15:10 UTC, Junkichi89 commented on src/CreateComponent/Create.css
> +  line-height: 28px;
こちら指定必要ですか？
不要なら削除しましょう。

2021-11-18 15:10 UTC, Junkichi89 commented on src/CreateComponent/Create.css
> +.status-container
まとめて指定するなら、一つのクラス名で汎用的に使ってもいいかと思います。
他も似たような記述が多かったりするので、一つにまとめられるものはまめておきましょう。

2021-11-18 15:10 UTC, Junkichi89 commented on src/CreateComponent/Create.css
> +  cursor: pointer;
不要では？

2021-11-18 15:10 UTC, Junkichi89 commented on src/CreateComponent/Create.css
> +  display: inline-block;
display: flexでいいと思いますよ。

2021-11-18 15:10 UTC, Junkichi89 commented on src/CreateComponent/Create.css
> +  cursor: pointer;
必要ですか？

2021-11-20 00:03 UTC, Junkichi89 commented
@MTaGn 
指摘した内容は全部確認されていますでしょうか？

指摘内容がわからず対応できなかった箇所については、コメントを残してもらえますか？
あと、対応したものは修正しましたなど入れておいてもらえると助かります。

すみませんがもう一度確認お願いします。

2021-11-20 00:37 UTC, MTaGn commented on src/CreateComponent/Create.css
> +}
不要なスタイルなため削除しました

2021-11-20 00:40 UTC, MTaGn commented on src/CreateComponent/Create.css
> +}
ヘッダーは西村さんにご対応いただけるとのことでヘッダーのスタイルは削除しました。
Create.jsのヘッダーのコードも削除するべきでしょうか？

2021-11-20 00:41 UTC, MTaGn commented on src/CreateComponent/Create.css
> +  margin: auto auto auto 56px;
ご指摘ありがとうございます。
西村さんにご担当いただける箇所ということで削除しました。

2021-11-20 00:41 UTC, MTaGn commented on src/CreateComponent/Create.css
> +  position: relative;
不要なため削除しました。

2021-11-20 00:43 UTC, MTaGn commented on src/CreateComponent/Create.css
> +  background-color: #4E758D;
ご指摘ありがとうございました。
削除しました。

2021-11-20 00:51 UTC, MTaGn commented on src/CreateComponent/Create.css
> +  line-height: 28px;
display: flex;　→削除しました
margint: 30px auto 30px 56px;　→デザインに基づきレイアウトするためにあてています
font-size: 24px;　→デザインに近づけるためにあてています。ないと追加ボタンの「追加」のテキストと同じフォントサイズになり、デザインと少しことなるものになります
line-height: 28px;　→削除しました

2021-11-20 00:54 UTC, MTaGn commented on src/CreateComponent/Create.css
> +  cursor: pointer;
display: inline-block;　→削除しました
  width: 163px;　→不要かもしれませんが、個人的にはデザインに近づけるためデフォルトより大きいセレクトボックスにするためにあてています
  height: 52px;　→上記widthと同様です
  cursor: pointer;　→削除しました

2021-11-20 00:58 UTC, MTaGn commented on src/CreateComponent/Create.css
> +  display: inline-block;
border: 1px solid #BEBABA;
  box-sizing: border-box;
  border-radius: 4px;
  display: inline-block;　→display: flex;を使用せずにすぐに対応できたためflexを使用していません。flexを使用したほうがいいでしょうか？

2021-11-20 01:00 UTC, MTaGn commented on src/CreateComponent/Create.css
> +  cursor: pointer;
display: inline-block;　→削除しました
  width: 163px;　→不要かもしれませんが、個人的にはデザインに近づけるためデフォルトより大きいセレクトボックスにするためにあてています
  height: 52px;　→　上記widthと同様です
  cursor: pointer;　→削除しました

2021-11-20 01:03 UTC, MTaGn commented
各コメントにリプライいたしました。

申し訳ございませんが、指摘していただいた箇所で修正もれがある箇所がわかりません。
ご教示お願いできないでしょうか。

2021-11-20 07:19 UTC, MTaGn commented
#2 
##表示方法：index.jsにをCreateコンポーネントをimportする

##対応内容：Create.jsのheader部分を削除、BreadCrumbコンポーネントインポート
##妥協点：Create.jsにheaderコンポーネントをインポートしていない

2021-11-20 10:45 UTC, Junkichi89 commented on src/CreateComponent/Create.css
> +}
はい、headerとbreadcrumbの記述は不要となります！
削除でお願いします。

2021-11-20 10:47 UTC, Junkichi89 commented on src/CreateComponent/Create.css
> +  line-height: 28px;
すみません、こちら、line-height: 28px;　だけの指摘でした、わかりづらくすみません。

2021-11-23 01:06 UTC, MTaGn commented
#2 create_add_page_fixed4_不要変数関数削除、最新mainのマージ

対応内容
〇Create.js
・BreadCrumbコンポーネント、使用していないstate、関数の削除
・最新mainをマージ

2021-11-23 22:33 UTC, MTaGn commented
#2 create_add_page_fixed5_作成画面遷移実装

対応内容
・Create.js, Create.cssのはいったCreateComponentごと削除
・routes下に上記と同じコードのCreate.jsを作成
・styles下に上記と同じコードのCreate.cssを作成
・App.jsでroutes下のCreate.jsをimportできるよう変更

2021-11-24 11:05 UTC, Junkichi89 requested changes
@MTaGn 
src/routes/Create.jsを削除して、作成した内容をsrc/routes/Create.jsxの中に反映させてください。
また、西村さんが作成しているsrc/routes/Create.jsxではパンクズリストが表示できているので、そちらを利用して、表示できるように設定してください。

修正終わりましたら、マージ可能となるかと思いますので、よろしくお願いします。

2021-11-25 00:31 UTC, Junkichi89 approved these changes
OKです！

LGTM！

![LGTM](https://image.lgtmoon.dev/147914)

2021-11-25 10:05 UTC, merged