#24_add_status_priority_update_feature
if-tech-support/todo_team pull request #31
Opened 2021-11-23 14:20 UTC by tetsu633

closes if-tech-support/todo_team#24

## IssueのURL
https://github.com/if-tech-support/todo_team/issues/24#issue-1054805230

## 対応内容・対応背景・妥協点
1. recoilでデータ管理するように変更
2. ステータスをボタン押下することで更新（未実施→実施中、実施中→完了、完了→未実施）するよう対応
3. 優先度をボタン押下することで更新（低→中、中→高、高→低）するよう対応

## やったこと
- atom.jsにダミーデータを移動、atom.jsからデータを取り出す、更新するように変更
- listview table ステータス, 優先度をpタグからbuttonタグへ変更
- button押下時の処理をそれぞれupdateTodoStatus, updateTodoPriorityに記載
  ボタン押下時にidを引数に取り、updateTodoStatus, updateTodoPriorityに渡す
  該当のtodoのみ値を変更するための処理をreplaceItemAtIndexに記載

## やってないこと
- 特になし

## UI before / after
- 特になし

## テスト
- console.logでステータス、優先度ボタン押下時のリストデータが更新されていることを確認

2021-11-24 11:20 UTC, Junkichi89 requested changes
@tetsu633 

動作については、問題ありませんでしたので、このままでもOKですが、
レベルアップという観点でいくならもう少し工夫できそうなところがありましたので、
指摘させていただきました。
頑張ってみてください！

2021-11-24 11:20 UTC, Junkichi89 commented on src/routes/ListView.jsx
> +  const [todoList, setTodoList] = useRecoilState(todoState);
todoStateよりtodoListStateの方が自然ではないでしょうか？

2021-11-24 11:20 UTC, Junkichi89 commented on src/routes/ListView.jsx
> +  };
こちらの内容について、カスタムhooksを作成してロジックの分離させることは可能でしょうか？
hooksディレクトリ配下にファイルを作成してもらう形で作成してもらえるといいかなと思います。
難しけれなそのままでもOKです。

参考
https://reffect.co.jp/react/react-custom-hook



また、以下の画像部分について、今回、Todoリストのstateをコピーをして複製してもらっていると思いますが、こちらではシャローコピーしか行えていないので、今後問題が発生する可能性があります。

あくまで今回の処理で修正が必要という意味ではないですが、知識として知っていてもらえたらいいかなというものです。知っていれば、無視してもらってOKです。
一応、参考の記事です。
シャローコピーとディープコピー
https://zenn.dev/luvmini511/articles/722cb85067d4e9
![image](https://user-images.githubusercontent.com/65665381/143227703-3d088990-c929-4a48-a4ab-dc3ed25156ea.png)

2021-11-24 11:20 UTC, Junkichi89 commented on src/routes/ListView.jsx
> +                      </button>
この辺が同じような記述が続いているので、まとめられるように工夫してみてもらえますか？
難しそうであれば、そのままでもOKです。

2021-11-25 10:26 UTC, tetsu633 commented
@Junkichi89 

### IssueのURL
[#24](https://github.com/if-tech-support/todo_team/issues/24#issue-1054805230)

### 対応内容・対応背景・妥協点
- todoStateからtodoListStateへ変更
  https://github.com/if-tech-support/todo_team/pull/31#discussion_r755566112

- カスタムhooksを利用してstatus, priorityをListViewから分離
  https://github.com/if-tech-support/todo_team/pull/31#discussion_r755580582

- status, priorityボタンをListViewから分離
  https://github.com/if-tech-support/todo_team/pull/31#discussion_r755956447

### やったこと
- useUpdateTodoStateでカスタムhookを作成しました
  返り値にupdateTodoStatusとupdateTodoPriority関数を返すようにし、関数を呼ぶだけで値を更新できるようにしてます

- status, priorityボタンのコンポーネントを用意してそこにボタンの描画処理を記載するようにしてます

### やってないこと
- スプレッド構文でのコピーはメモリーの共有だとは知りませんでした、しかもObject.assign()もなんですね！
  今回は対応してませんがいただいた資料には文字列化し、またオブジェクトに戻すことでディープコピーをしているとのことで勉強になりました
  ただし対応できない場合もあるとのことなので色々面倒そうですね、、、

### UI before / after
- 特になし

### テスト
- 特になし

2021-11-25 14:10 UTC, Junkichi89 requested changes
custom hookいい感じですね！！
だいぶスッキリしました！

まだ効率的に書けそうなところがあったので、指摘させていただきました。
修正よろしくお願いします！

2021-11-25 14:10 UTC, Junkichi89 commented on src/components/StatusButton.jsx
> +  const { updateTodoStatus } = useUpdateTodoState();
もう少し良くするなら、こんな形で書いてもいけると思います！
優先度の方も直してもらえるといいですかね。
定数については、別ファイルにしてimportしてもいいかもです！
``` jsx
import useUpdateTodoState from "../hooks/useUpdateTodoState";

const StatusButton = ({ todo }) => {

  const BUTTON_STYLE = {
    未着手: 'table-content-status table-content-status-pending',
    作業中: 'table-content-status table-content-status-working',
    完了: 'table-content-status table-content-status-working',
  };
  // ステータス更新用カスタムフック
  const { updateTodoStatus } = useUpdateTodoState();
  return (
    <>
      <button
        className={BUTTON_STYLE[todo.status]}
        onClick={() => {
          updateTodoStatus(todo.id);
        }}
      >
        {todo.status}
      </button>
    </>
  );
};

export default StatusButton;
```

2021-11-26 11:34 UTC, tetsu633 commented
@Junkichi89

## IssueのURL
#24

## 対応内容・対応背景・妥協点
- 優先度、ステータスボタンのクラスをリファクタリング
- 優先度、ステータスを定数で設定

## やったこと
- ボタンのクラスをStyle用のオブジェクトに格納してます
- constants.jsに優先度、ステータスを定数で保持するようにしています

## やってないこと
- 特になし

## UI before / after
- 特になし

## テスト
- 特になし

2021-11-28 05:48 UTC, tetsu633 commented
@Junkichi89

### IssueのURL
#24

### 対応内容・対応背景・妥協点
- 優先度、ステータスボタンのクラスをリファクタリング
- 優先度、ステータスを定数で設定

### やったこと
- ボタンのクラスをStyle用のオブジェクトに格納してます
- constants.jsに優先度、ステータスを定数で保持するようにしています

### やってないこと
- 特になし

### UI before / after
- 特になし

### テスト
- 特になし

2021-11-28 10:56 UTC, Junkichi89 approved these changes
@tetsu633 

実装お疲れ様でした。

OKです！
マージお願いします！
![LGTM](https://image.lgtmoon.dev/117129)

2021-11-28 13:05 UTC, merged