#3_add_editpage
if-tech-support/todo_team pull request #32
Opened 2021-11-29 23:53 UTC by tetsu633

closes #3

### IssueのURL
https://github.com/if-tech-support/todo_team/issues/3#issue-1042955301

### 対応内容・対応背景・妥協点
- 編集画面のレイアウト作成

### やったこと
- 編集画面のレイアウト作成
- 他の画面のCSSが影響して意図しないレイアウトになってしまうためclass名をedit__**といったように記述しています

### やってないこと
- 特になし

### UI before / after
- 特になし

### テスト
- 特になし

2021-12-04 03:54 UTC, tetsu633 commented
closes #7

## IssueのURL
https://github.com/if-tech-support/todo_team/issues/7#issue-1042970064

## 対応内容・対応背景・妥協点
- 編集画面機能実装

## やったこと
- リストビューでtodo押下時にnavigateで画面遷移
   propsに押下したtodoを渡すようにしています
   画面遷移後のurlにidが入るようrouterの設定を変更（その際にrouterはapp.jsからrouter.jsに切り離すようにしました）

- todoの更新・削除の処理はカスタムフックuseUpdateTodoに記載
  更新日のフォーマットはutilities.jsに記載

## やってないこと
- ステータス、優先度が空（-----------）は考慮する必要ありますでしょうか？
   基本何かしらのステータス、優先度が入る想定で作成してます

## UI before / after
- 特になし

## テスト
- コンソールでの確認
- 削除、保存、戻るボタンの挙動確認
- タイトル、詳細、ステータス選択肢、優先度選択肢が編集できることを確認

2021-12-04 13:01 UTC, Junkichi89 requested changes
実装お疲れさまでした。

> ステータス、優先度が空（-----------）は考慮する必要ありますでしょうか？
> 基本何かしらのステータス、優先度が入る想定で作成してます

こちら現状の実装で問題ないです。
------含めるとすると、バリデーションをかけて保存できないようにしないといけないと言う感じで工数がかさむので、このままでOKです。

細かなところ指摘させていただきました。
全体的に綺麗にまとまてもらってみやすかったです。

関数などがhooksに分離されているので非常にコードが追いやすく、レビューしやすいと思いました。

個人的に気になったところを指摘させていただきましたので、確認お願いします。

2021-12-04 13:01 UTC, Junkichi89 commented on src/hooks/useUpdateTodo.jsx
> +    navigation("/");
navigationはコンポーネント内で呼び出す形でいいと思います。
そうすれば他でも使い回しがしやすくなるかなと思いました。
今回のTodoでは特に編集は一箇所しかないので、修正してもしなくても大丈夫かなと思います。

2021-12-04 13:01 UTC, Junkichi89 commented on src/hooks/useUpdateTodo.jsx
> +    navigation("/");
deleteは他でも使用できるといいのかなと思うので、navigationhはこちらに含めないように
してもらえるといいかなと思います。
（削除機能は他のissueだったので、本来ならそちらを使用してもらえるように作れるとよかったのですが、作業の進捗上、こういうケースもあるのかなと思います。）

今回は編集ページだけで使えるhooksとして作ってもらっているかと思います。（issueとしては、これで正解です。）
ただ、他の箇所でも作れるように作ってもらえると、他の実装者が幸せになれるのかなと思いました。
updateの中のdelete機能ではなく、delete機能としてhooks作ってしまってもいいかなと思いました。

2021-12-04 13:01 UTC, Junkichi89 commented on src/utilities.js
> +export const createUpdateTime = () => {
utilitiesディレクトリを作ってしまって、その中でcreateupdateTimeというファイルを作ってしまってもいいと思います。
命名などは任せます。

src直下だとjsが並んでいて分かりづらい気がしました！

2021-12-05 09:38 UTC, tetsu633 commented
## IssueのURL
#7 (comment)

## 対応内容・対応背景・妥協点
- 編集画面機能 リファクタリング

## やったこと
- todo削除用カスタムフック、todo更新用カスタムフック実装を別のカスタムフックに作成
- 日付フォーマット用の関数をutilsフォルダの配下にcurrentDateFormatter.jsに記述
- 画面遷移の処理をコンポーネントに記述

## やってないこと
- 特になし

## UI before / after
- 特になし

## テスト
- 画面での挙動の確認
- コンソールの確認

2021-12-06 13:10 UTC, Junkichi89 approved these changes
OKです！
LGTM！

![LGTM](https://image.lgtmoon.dev/149294)

2021-12-06 13:35 UTC, merged