#5 create func
if-tech-support/todo_team pull request #33
Opened 2021-12-01 13:18 UTC by MTaGn

## IssueのURL
https://github.com/if-tech-support/todo_team/issues/5
## 対応内容・対応背景・妥協点
・ListViewから「タスクを追加」ボタン押下後作成画面に遷移
・入力したタイトル・内容・優先度・id・作成日時・更新日時をrecoilで状態管理
・idは一意の値を取得
・作成画面の「追加」ボタン押下後に一覧画面に遷移
〇妥協点
・タイトル・内容・idをuseStateのinputTodosにまとめたかったが、方法が思いつかずそれぞれuseStateで状態管理している
## やってないこと・できていないこと
・タイトル・内容・idをuseStateのinputTodosにまとめたかったが、方法が思いつかずそれぞれuseStateで状態管理している

## テスト
todoを追加後にリロードしてもリセットされていないことを確認

## レビュー観点
・タイトル・内容・idをuseStateのinputTodosにまとめたかったが、方法が思いつかずそれぞれuseStateで状態管理している点
(前回のミーテイングで西村さんに指摘された箇所)

2021-12-01 23:07 UTC, Junkichi89 commented on src/routes/Create.jsx
> +  const [todo, setTodoList] = useRecoilState(inputState)
todoなのか、todoListなのか混乱してしまうので、
todoなら setTodo
todoListならsetTodoListにしましょう。

2021-12-01 23:13 UTC, Junkichi89 commented on src/routes/Create.jsx
> +  const [todoId, setTodoId] = useState(0)
IDはTodoList（配列）のlengthを使ってみてはどうでしょうか？

2021-12-01 23:39 UTC, Junkichi89 requested changes
まず、プルリクエストを作成する前に必ずmainをpullするようにしてください。
追加を押した後にTodoが追加されて一覧画面のTodoリストに反映するように実装してください。

inputのstateに関して、先週、西村さんからアドバイスいただいた内容が反映されていないように思います。
修正可能でしょうか？

定義しているのに使用していないものがあるので必要なものだけ定義するように気をつけてもらえるといいかと思います。
※プルリク前にブラウザのコンソールは必ず確認してください（以下画像参照）

![image](https://user-images.githubusercontent.com/65665381/144330523-1ed608f4-0bd7-435e-b45e-c2918c317612.png)

命名に関してreactのルールを無視してしまっているところがあるので、気をつけてください。
```
const [inputTodos, setTodos] = useState([])
```
上記など・・・

また、変数名やidを取得する関数などもう少し、他の人がみてもわかりやすいようにコメントを入れたり、命名をわかりやすくしてもらえるといいと思います。


上記を踏まえた上で、修正を行ってもらえますでしょうか？
よろしくお願いします。

2021-12-01 23:39 UTC, Junkichi89 commented on src/routes/Create.jsx
> +    const inputTodosForInput = [...oldData, { id: todoId, title: todoTitle, detail: todoDetail, priority: todoPriority, updatedAt:today, createdAt:today }]
これoldDataを使っている理由ってありますか？
理由があって使用しているなら教えていただけますか？

2021-12-02 03:37 UTC, MTaGn commented on src/routes/Create.jsx
> +    const inputTodosForInput = [...oldData, { id: todoId, title: todoTitle, detail: todoDetail, priority: todoPriority, updatedAt:today, createdAt:today }]
atomに入っているtodoのデータに新たに追加したいデータを追加し、atomのデータを更新する方法をとっています。既存のtodoのデータに追加したいデータだけを追加する方法がわからなかったため上記の方法をとっています。

2021-12-02 16:10 UTC, MTaGn commented on src/routes/Create.jsx
> +  const [todo, setTodoList] = useRecoilState(inputState)
命名のルールに従った名前に修正しました

2021-12-02 16:11 UTC, MTaGn commented on src/routes/Create.jsx
> +  const [todoId, setTodoId] = useState(0)
lengthを使用して取得しました

2021-12-03 03:39 UTC, MTaGn commented
〇対応内容
・main最新化
・mainを#5_create_funcにマージした際のコンフリクト解消
・追加する値を1つのstateで状態管理するように修正
・idの取得方法を変更
〇テスト
・リロードしてもtodoデータが消えていないことを確認
・id・タイトル・内容・ステータス・優先度・作成更新日時が状態管理されているかコンソールで確認

2021-12-03 13:11 UTC, MTaGn commented
対応内容・対応背景・妥協点
・作成画面にて追加したtodoデータをListViewにて表示

テスト
・リロードしてもリセットされていないことを確認

UI
・特になし

2021-12-04 11:44 UTC, Junkichi89 commented on src/routes/Create.jsx
> +import { inputState } from "../atoms/atom";
inputStateの初期値がtestとなっているせいで、エラーになってしまっていますので、調整お願いします。

2021-12-04 11:48 UTC, Junkichi89 commented on src/routes/Create.jsx
> +    const today = year+"-"+month+"-"+day+" "+hour+":"+minute+":"+second
こちらは別ロジックに切り分けた方がいいかなと思います。
修正お願いします。

2021-12-04 12:01 UTC, Junkichi89 requested changes
実装お疲れさまです。
atomに設定しているinputStateは、確認で設定したものなので、使用する際は用途に合わせて修正いただければと思います。
todoListStateを編集してもらって使ってもらえるといいかなと思いました。

同じようなコメントしてますが、意図を汲み取ってもらえると幸いです。
よろしくお願いします。

2021-12-04 12:01 UTC, Junkichi89 commented on src/routes/Create.jsx
> +              console.log(e.target.value)
確認用のコンソールログはプルリク前に削除するようにお願いします。

2021-12-04 12:01 UTC, Junkichi89 commented on src/routes/ListView.jsx
> +import { inputState } from "../atoms/atom";
inputStateの初期値がエラーの原因になっているので調整お願いします。
todoListStateを使って貰えばいいかなと思いますが、detailが含まれていないので、使用するなら追加してもらえますか？

2021-12-04 12:01 UTC, Junkichi89 commented on src/routes/ListView.jsx
> +  const todoList = useRecoilValue(inputState);
上記のコメントに合わせて修正お願いします。

2021-12-06 13:38 UTC, Junkichi89 reviewed
```
 <label for='title' className='task-label input-area-label label'>
              タスク名 :
</label>

2021-12-06 13:38 UTC, Junkichi89 commented on src/utilities/CreateUpdateTime.js
> +export const CreateUpdateTime = () => {
関数名は小文字スタートでいいと思います。

2021-12-06 13:38 UTC, Junkichi89 commented on src/atoms/atom.js
>        createAt: "2020-11-8 18:55:07",
listViewではcreatedAtとなっているので初期状態で表示されていないです。
確認お願いします。

2021-12-06 13:38 UTC, Junkichi89 commented on src/routes/ListView.jsx
> +                  <td>{todo.createdAt}</td>
atomの値と一致しないので初期データ表示されていないので確認してください。

2021-12-06 14:39 UTC, Junkichi89 requested changes
気になっていろいろと指摘してしまいました。
不要なコードがまだ残っていたりするので、もう少し改善点はないか、
見直してもらえるといいと思いました！

メソッドの使い方を工夫できるともっとみやすいコードが書けると思います！
指摘が重複していて分かりづらいところは質問してもらえると幸いです。

mainを最新にして、pullしてから修正を行うようにお願いします。
(西村さんのissueの内容と影響範囲が重なっている箇所がありますので)

2021-12-06 14:39 UTC, Junkichi89 commented on src/routes/Create.jsx
> +  }
この処理について、別ファイルに分けてしまっても大丈夫だと思います。

```
     const res = todoList.map((todo) => {
      // idだけ取得
      const idArray = []
      idArray.push(todo.id)

      return idArray
    })
```

ここの部分はもう少し命名なども含めて分かりやすく書いてもらえるといいと思います。
個人的には、idだけの配列を作るなら

```

     const idArray = todoList.map(({id}) => {
      return id
    })

```

でいいように思います。
他にも方法はあると思うので、より良い方法を考えてみてください！

2021-12-06 14:39 UTC, Junkichi89 commented on src/routes/Create.jsx
> +     id: getInputId(),
ここに入れてしまうとinputTodoが更新される度に`getInputId()`が呼び出されてしまうので、
別の場所でidを設定した方がいいと思います。
修正お願いします。

2021-12-06 14:39 UTC, Junkichi89 commented on src/routes/Create.jsx
> +    setTodoList([...todoList, {...inputTodo, ...{createdAt:today, updatedAt:today} }])
```
...{createdAt:today, updatedAt:today}
```

このオブジェクトとスプレッド構文は必要でしょうか？
確認お願いします！

2021-12-06 14:39 UTC, Junkichi89 commented on src/utilities/CreateUpdateTime.js
> +export const CreateUpdateTime = () => {
getの方が自然なような気もしますが、西村さん作っているものと被っているので、
mainをpullして西村さん作成してくれたものを使用するか、
自分が作成したものを使いたい場合は、西村さんが作成しているところを修正しないといけないです。

どちらを選択してもらってもいいですが、後者の場合は、他の人が作成したコードをいじることになるので、
注意が必要です。
修正お願いします。

2021-12-06 14:39 UTC, Junkichi89 commented on src/routes/Create.jsx
> +     updatedAt:'',
ここもなくて良さそうですね。

2021-12-07 15:58 UTC, MTaGn commented
IssueのURL
#5

対応内容・対応背景・妥協点
・mainマージ時のコンフリクト解消
・getInputId関数の別ファイルへの切り離し
〇妥協点
・特になし

やってないこと・できていないこと
・特になし

テスト
todoを追加後にリロードしてもリセットされていないことを確認

レビュー観点
・getInputId関数をutilsディレクトリ下に配置しましたが、ここであってますでしょうか

2021-12-09 09:51 UTC, Junkichi89 reviewed
OKです！
一点だけ、labelの修正(for→htmlFor)だけお願いします。

> レビュー観点
> ・getInputId関数をutilsディレクトリ下に配置しましたが、ここであってますでしょうか

こちらで問題ないですね！
近い回ししやすくなると思います！

2021-12-09 09:51 UTC, Junkichi89 commented on src/routes/Create.jsx
>                内容 :
ここのlabelもhtmlForにしておきましょうか！

2021-12-09 12:47 UTC, MTaGn commented
IssueのURL
#5

対応内容・対応背景・妥協点
・labelタグのfor→htmlForに変更
・最新mainブランチをマージ

2021-12-09 14:28 UTC, Junkichi89 approved these changes
LGTMです！
お疲れ様でした！

![LGTM](https://image.lgtmoon.dev/8402)

2021-12-09 15:28 UTC, merged